import { tracedGenerateObject as generateObject } from "../lib/langsmith";
import gemini from "../lib/ai_config";
import {
  createSlopMetrics,
  SlopAnalysisOutputSchema,
  type SlopPattern,
  type SlopReport,
  type SlopCategory,
} from "@humanish/shared";

export class SlopAnalyzerService {
  /**
   * Analyze changed files for AI slop patterns.
   * Returns a structured SlopReport or null if analysis fails.
   *
   * This is designed to NEVER throw - all errors are caught and return null.
   */
  async analyze(
    fileContents: Map<string, string>,
    task: string
  ): Promise<SlopReport | null> {
    try {
      if (fileContents.size === 0) {
        console.log("[SlopAnalysis] No files to analyze");
        return null;
      }

      console.log(
        `[SlopAnalysis] Analyzing ${fileContents.size} file(s) for AI slop...`
      );

      const prompt = this.buildAnalysisPrompt(fileContents, task);

      const startTime = Date.now();
      const result = await generateObject({
        model: gemini,
        schema: SlopAnalysisOutputSchema,
        prompt,
        temperature: 0.1,
      });
      const elapsed = Date.now() - startTime;

      console.log(`[SlopAnalysis] Analysis completed in ${elapsed}ms`);

      const { patterns, summary, canAutoFix } = result.object;
      const report = this.buildReport(patterns, summary, canAutoFix);

      if (patterns.length === 0) {
        console.log(
          `[SlopAnalysis] No slop patterns found - feature scored ${report.humanishScore}% Humanish`
        );
        return report;
      }

      console.log(
        `[SlopAnalysis] Found ${report.totalCount} issue(s): ` +
          `${report.criticalCount} critical, ` +
          `across ${Object.keys(report.byFile).length} file(s), ` +
          `score ${report.humanishScore}%`
      );

      const criticalPatterns = patterns.filter(
        (pattern) =>
          pattern.severity === "critical" || pattern.severity === "high"
      );

      if (criticalPatterns.length > 0) {
        console.log("[SlopAnalysis] Critical/High findings:");
        criticalPatterns.forEach((pattern) => {
          console.log(
            `  [${pattern.severity.toUpperCase()}] ${pattern.category} in ${pattern.file}:${pattern.line ?? "?"} - ${pattern.description}`
          );
        });
      }

      return report;
    } catch (error) {
      console.error(
        "[SlopAnalysis] Analysis failed (non-blocking):",
        error instanceof Error ? error.message : String(error)
      );
      return null;
    }
  }

  private buildReport(
    patterns: SlopPattern[],
    summary: string,
    canAutoFix: boolean
  ): SlopReport {
    const byCategory: Partial<Record<SlopCategory, SlopPattern[]>> = {};
    const byFile: Record<string, SlopPattern[]> = {};

    for (const pattern of patterns) {
      if (!byCategory[pattern.category]) {
        byCategory[pattern.category] = [];
      }
      byCategory[pattern.category]!.push(pattern);

      if (!byFile[pattern.file]) {
        byFile[pattern.file] = [];
      }
      byFile[pattern.file]!.push(pattern);
    }

    const criticalCount = patterns.filter(
      (pattern) => pattern.severity === "critical"
    ).length;

    return {
      totalCount: patterns.length,
      criticalCount,
      byCategory,
      byFile,
      summary:
        summary ||
        (patterns.length === 0
          ? "No AI slop detected. This feature looks production-ready and Humanish."
          : "AI slop detected. Review the findings below."),
      canAutoFix,
      ...createSlopMetrics(patterns),
    };
  }

  private buildAnalysisPrompt(
    fileContents: Map<string, string>,
    task: string
  ): string {
    let filesSection = "";
    fileContents.forEach((content, path) => {
      const lineCount = content.split("\n").length;
      filesSection += `\n=== FILE: ${path} (${lineCount} lines) ===\n\`\`\`\n${content}\n\`\`\`\n\n`;
    });

    return `You are a senior code reviewer specializing in detecting AI-generated code quality issues ("AI slop").

## Task Context
The following code was generated by an AI to accomplish this task:
"${task}"

## Your Job
Analyze the code below for AI slop - issues that compile and may pass basic tests but will cause problems in production. Be thorough but avoid false positives. Only flag real problems.

## Categories to Check

### 1. Logic Bugs & Edge Cases (category: "logic_bug")
- Off-by-one errors in loops or array indexing
- Unhandled null/undefined values
- Async/await missing or incorrectly used (race conditions, unhandled rejections)
- Wrong boolean logic (inverted conditions, missing cases)
- Missing error handling for operations that can fail

### 2. Security Issues (category: "security")
- Hardcoded secrets, API keys, or passwords
- SQL injection or command injection vulnerabilities
- Missing input validation on user-facing endpoints
- Sensitive data exposed in logs or error messages
- Missing authentication/authorization checks
- CORS misconfiguration

### 3. Code Quality (category: "code_quality")
- Functions longer than 50 lines (God functions)
- Deeply nested logic (> 3 levels)
- Poor naming: overly generic names like data, result, temp, item
- Unnecessary abstraction layers (wrapper functions that just call one thing)
- Duplicated logic that should be extracted
- Inconsistent coding patterns within the same file

### 4. Inefficiency (category: "inefficiency")
- N+1 database queries
- Unnecessary loops or redundant iterations
- Synchronous operations that should be async
- Dead code (variables declared but never used, unreachable code paths)
- Bloated implementations (10 lines for what could be 2)

### 5. Context Mismatch (category: "context_mismatch")
- Code that duplicates utility functions visible in other files
- Patterns that conflict with the project's existing conventions
- Adding dependencies that are unnecessary given what's already available
- Ignoring existing error handling patterns used elsewhere in the project

## Severity Levels
- critical: Security vulnerabilities or logic bugs that will cause data loss/corruption
- high: Logic bugs that will cause incorrect behavior in production
- medium: Code quality issues that increase maintenance burden
- low: Minor inefficiencies or style issues

## Rules
1. Each finding MUST include a concrete, actionable suggestion - not just "fix this"
2. The snippet field must contain the exact code from the source
3. Do NOT flag issues that are standard patterns for the framework being used
4. Do NOT flag missing tests or documentation
5. If the code is genuinely clean, return an empty patterns array
6. Be specific about line numbers when possible

## Files to Analyze
${filesSection}

Analyze all files above and return your findings.`;
  }
}
